Repository nav-solutions/rinex, pull requests merged in 2023-08, with the labels that each got.

#104 carrier signal: improve signal identification
  rinex/src/carrier.rs
Labels: enhancement, bug-fix

#120 improve readme and docrs
  README.md
  rinex/README.md
  rinex/src/lib.rs
Labels: documentation, enhancement

#116 Simplify record iteration with new methods
  README.md
  rinex-cli/src/analysis/epoch_histogram.rs
  rinex-cli/src/analysis/mod.rs
  rinex-cli/src/analysis/sampling.rs
  rinex-cli/src/analysis/sv_epoch.rs
  rinex-cli/src/cli.rs
  rinex-cli/src/identification.rs
  rinex-cli/src/main.rs
  rinex-cli/src/plot/record/observation.rs
  rinex-cli/src/plot/skyplot.rs
  rinex/Cargo.toml
  rinex/src/algorithm/filters/decim.rs
  rinex/src/algorithm/filters/mask.rs
  rinex/src/algorithm/target.rs
  rinex/src/epoch/flag.rs
  rinex/src/lib.rs
  rinex/src/meteo/record.rs
  rinex/src/navigation/eopmessage.rs
  rinex/src/navigation/ephemeris.rs
  rinex/src/navigation/ionmessage.rs
  rinex/src/navigation/mod.rs
  rinex/src/navigation/record.rs
  rinex/src/navigation/stomessage.rs
  rinex/src/observable.rs
  rinex/src/observation/record.rs
  rinex/src/qc/analysis/mod.rs
  rinex/src/qc/analysis/obs.rs
  rinex/src/qc/analysis/sampling.rs
  rinex/src/qc/analysis/sv.rs
  rinex/src/qc/mod.rs
  rinex/src/qc/opts.rs
  rinex/src/record.rs
  rinex/src/split.rs
  rinex/tests/clocks.rs
  rinex/tests/decompression.rs
  rinex/tests/masking.rs
  rinex/tests/meteo.rs
  rinex/tests/nav.rs
  rinex/tests/obs.rs
  rinex/tests/parsing.rs
  rinex/tests/sampling.rs
  tools/sv_elev_azim.py
Labels: enhancement, v1.0.0, feature

#121 rinex-cli: deprecated options, prefer preprocessing filter designer
  rinex-cli/doc/sampling.md
  rinex-cli/src/cli.rs
  rinex-cli/src/main.rs
Labels: enhancement

#122 rinex v0.11.0
  rinex-cli/Cargo.toml
  rinex/Cargo.toml
Labels: documentation, enhancement, bug-fix

#123 fix feature definition
  .github/workflows/rust.yml
  rinex/src/ionex/record.rs
  rinex/src/lib.rs
  rinex/src/navigation/record.rs
  rinex/src/record.rs
Labels: bug-fix

#126 improve documentation
  rinex/src/lib.rs
Labels: documentation, enhancement, v1.0.0

#127 update minimum rustc requirement
  README.md
  rinex-cli/Cargo.toml
  rinex/Cargo.toml
  rinex/README.md
Labels: documentation

#129 rinex: v0.11.1
  rinex/Cargo.toml
Labels: enhancement, bug-fix

#130 fix kepler solver and skyplot view
  doc/plots/skyplot.png
  rinex-cli/Cargo.toml
  rinex-cli/README.md
  rinex-cli/doc/skyplot.md
  rinex-cli/src/plot/skyplot.rs
  rinex/db/NAV/orbits.json
  rinex/src/ground_position.rs
  rinex/src/lib.rs
  rinex/src/navigation/ephemeris.rs
  rinex/src/navigation/orbits.rs
  rinex/src/navigation/record.rs
  tools/sv_elev_azim.py
Labels: enhancement, bug-fix

#131 simplify and improve week counter definitions
  rinex/db/NAV/orbits.json
  rinex/src/navigation/ephemeris.rs
  rinex/src/navigation/record.rs
Labels: enhancement

#132 glonass and sbas positioning
  rinex/src/navigation/ephemeris.rs
Labels: enhancement, bug-fix

#135 NAV V4: RINEX V4 navigation support
  rinex/build.rs
  rinex/db/NAV/orbits.json
  rinex/src/algorithm/target.rs
  rinex/src/navigation/ephemeris.rs
  rinex/src/navigation/orbits.rs
  rinex/src/navigation/record.rs
  rinex/src/version.rs
  rinex/tests/nav.rs
Labels: enhancement, v1.0.0, feature

#136 support NAV V4 frames
  rinex/db/NAV/orbits.json
  rinex/src/navigation/ephemeris.rs
  rinex/src/navigation/orbits.rs
  rinex/src/navigation/record.rs
  rinex/tests/nav.rs
Labels: enhancement, v1.0.0, bug-fix

#137 Bibliography
  README.md
  rinex/README.md
  rinex/src/bibliography.rs
  rinex/src/lib.rs
  rinex/src/navigation/ephemeris.rs
  rinex/src/navigation/record.rs
  rinex/src/observation/mod.rs
Labels: documentation, enhancement

#138 cli: enhance nav file options
  doc/plots/skyplot.png
  doc/plots/sv_clocks.png
  rinex-cli/README.md
  rinex-cli/src/main.rs
  rinex-cli/src/plot/mod.rs
  rinex-cli/src/plot/record/mod.rs
  rinex-cli/src/plot/record/navigation.rs
Labels: documentation, enhancement, bug-fix

#139 Release v0.12.0
  doc/plots/esbc00dnk_ssi.png
  rinex-cli/README.md
  rinex-cli/src/plot/record/navigation.rs
  rinex-cli/src/plot/record/observation.rs
  rinex/Cargo.toml
  rinex/src/navigation/record.rs
Labels: documentation, enhancement, bug-fix

#140 Improve qc context definition and reporting
  rinex-cli/.gitignore
  rinex-cli/README.md
  rinex-cli/doc/qc.md
  rinex-cli/src/analysis/sampling.rs
  rinex-cli/src/analysis/sv_epoch.rs
  rinex-cli/src/cli.rs
  rinex-cli/src/context.rs
  rinex-cli/src/fops.rs
  rinex-cli/src/identification.rs
  rinex-cli/src/main.rs
  rinex-cli/src/parser.rs
  rinex-cli/src/plot/combination.rs
  rinex-cli/src/plot/mod.rs
  rinex-cli/src/plot/record/ionex.rs
  rinex-cli/src/plot/record/meteo.rs
  rinex-cli/src/plot/record/navigation.rs
  rinex-cli/src/plot/record/observation.rs
  rinex-cli/src/plot/skyplot.rs
  rinex-cli/src/preprocessing.rs
  rinex-cli/workspace/.gitkeep
  rinex/src/hardware.rs
  rinex/src/header.rs
  rinex/src/lib.rs
  rinex/src/qc/analysis/mod.rs
  rinex/src/qc/analysis/obs.rs
  rinex/src/qc/analysis/sampling.rs
  rinex/src/qc/analysis/sv.rs
  rinex/src/qc/context.rs
  rinex/src/qc/mod.rs
  rinex/src/qc/navigation.rs
  rinex/src/qc/observation.rs
  rinex/src/qc/opts.rs
  rinex/src/types.rs
  rinex/tests/antex.rs
  rinex/tests/parsing.rs
Labels: enhancement

#141 Introduce observation data iterators
  rinex/src/lib.rs
  rinex/tests/obs.rs
Labels: enhancement

#149 Fix RINEX v4 mistakes in orbits.json
  rinex/db/NAV/orbits.json
Labels: enhancement, bug-fix

#148 fix nav-v4 support
  rinex/db/NAV/orbits.json
  rinex/tests/nav.rs
  rinex/tests/parsing.rs
  test_resources/NAV/V4/BRD400DLR_S_20230710000_01D_MN.rnx.gz
Labels: enhancement, v1.0.0, bug-fix, coverage

#151 improve test ecosystem
  .github/workflows/rust.yml
  .gitignore
  rinex/Cargo.toml
  rinex/src/lib.rs
  rinex/src/merge.rs
  rinex/src/tests/antex.rs
  rinex/src/tests/clocks.rs
  rinex/src/tests/compression.rs
  rinex/src/tests/decompression.rs
  rinex/src/tests/ionex.rs
  rinex/src/tests/masking.rs
  rinex/src/tests/merge.rs
  rinex/src/tests/meteo.rs
  rinex/src/tests/mod.rs
  rinex/src/tests/nav.rs
  rinex/src/tests/obs.rs
  rinex/src/tests/parsing.rs
  rinex/src/tests/production.rs
  rinex/src/tests/sampling.rs
  rinex/src/tests/smoothing.rs
  rinex/src/tests/stats.rs
  rinex/src/tests/toolkit.rs
  rinex/tests/merge.rs
Labels: enhancement

#153 sp3 context
  rinex-cli/Cargo.toml
  rinex-cli/README.md
  rinex-cli/doc/file-combination.md
  rinex-cli/src/cli.rs
  rinex-cli/src/main.rs
  rinex-cli/src/plot/mod.rs
  rinex-cli/src/plot/record/mod.rs
  rinex-cli/src/plot/record/sp3.rs
  rinex/Cargo.toml
  rinex/src/qc/context.rs
Labels: documentation, enhancement, v1.0.0
