Repository nav-solutions/rinex, pull requests merged in 2024-04, with the labels that each got.

#231 Fix empty constellation case (old RINEX format)
  rinex/src/header.rs
Labels: bug-fix

#232 DORIS RINEX
  rinex-cli/src/cli/fops/filegen.rs
  rinex-cli/src/cli/mod.rs
  rinex/Cargo.toml
  rinex/src/carrier.rs
  rinex/src/context.rs
  rinex/src/cospar.rs
  rinex/src/domes.rs
  rinex/src/doris/mod.rs
  rinex/src/doris/record.rs
  rinex/src/doris/station.rs
  rinex/src/epoch.rs
  rinex/src/header.rs
  rinex/src/lib.rs
  rinex/src/merge.rs
  rinex/src/observable.rs
  rinex/src/observation/mod.rs
  rinex/src/record.rs
  rinex/src/tests/doris.rs
  rinex/src/tests/mod.rs
  rinex/src/tests/obs.rs
  rinex/src/tests/toolkit/doris.rs
  rinex/src/tests/toolkit/mod.rs
  rinex/src/tests/toolkit/observation.rs
  rinex/src/types.rs
  test_resources/DOR/V3/cs2rx18164.gz
Labels: enhancement, v1.0.0, performance

#239 RINEX v2 ionosphere parameter parsing
  rinex-cli/src/positioning/mod.rs
  rinex/src/header.rs
  rinex/src/lib.rs
  rinex/src/navigation/ionmessage.rs
  rinex/src/tests/nav.rs
  rinex/src/tests/parsing.rs
  rinex/src/tests/toolkit/mod.rs
  rinex/src/tests/toolkit/nav.rs
  test_resources/NAV/V2/cbw10010.21n.gz
Labels: documentation, enhancement, good first issue, bug-fix

#235 V0.16
  Cargo.toml
  crx2rnx/Cargo.toml
  rinex-cli/Cargo.toml
  rinex-cli/src/cli/fops/filegen.rs
  rinex-cli/src/cli/mod.rs
  rinex-cli/src/positioning/cggtts/mod.rs
  rinex-cli/src/positioning/interp/orbit.rs
  rinex-cli/src/positioning/interp/time.rs
  rinex-cli/src/positioning/mod.rs
  rinex-cli/src/positioning/ppp/mod.rs
  rinex-qc/Cargo.toml
  rinex/Cargo.toml
  rinex/src/cospar.rs
  rinex/src/doris/record.rs
  rinex/src/lib.rs
  rinex/src/record.rs
  rinex/src/tests/doris.rs
  rinex/src/tests/nav.rs
  rnx2crx/Cargo.toml
  sinex/Cargo.toml
  ublox-rnx/Cargo.toml
Labels: documentation, enhancement, performance, dependencies, bug-fix
